# Generated by Django 5.1.7 on 2025-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empresa', models.CharField(max_length=100)),
                ('lugar_entrega', models.CharField(max_length=200)),
                ('cantidad_radios', models.IntegerField()),
                ('excursion', models.CharField(max_length=100)),
                ('guia', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('confirmado', '🟢 Confirmado'), ('entregado', '🔵 Entregado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('almacen', models.CharField(choices=[('principal', 'Almacén Principal'), ('secundario', 'Almacén Secundario'), ('reserva', 'Almacén de Reserva')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('prioridad', models.CharField(choices=[('alta', '🔥 Alta'), ('media', '⚠️ Media'), ('baja', '💤 Baja')], default='media', max_length=20)),
                ('realizada', models.BooleanField(default=False)),
            ],
        ),
    ]
