# Generated by Django 5.1.7 on 2025-03-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_especifica',
            field=models.DateField(blank=True, null=True),
        ),
    ]
