# Generated by Django 5.1.7 on 2025-05-12 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_fecha_creacion_alter_pedido_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
