# Generated by Django 5.1.7 on 2025-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_tarea_fecha_especifica'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.CharField(max_length=100, verbose_name='PAX')),
                ('lugar_er', models.CharField(max_length=200, verbose_name='Lugar de E/R')),
                ('excursion', models.CharField(max_length=200, verbose_name='Excursión')),
                ('guia', models.CharField(max_length=100, verbose_name='Guía')),
                ('fecha_er', models.DateField(verbose_name='Fecha de E/R')),
                ('entregado', models.BooleanField(default=False, verbose_name='E')),
                ('recogido', models.BooleanField(default=False, verbose_name='R')),
            ],
        ),
    ]
