# Generated by Django 5.1.7 on 2025-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_stockcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='excursion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='fecha_er',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='guia',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='lugar_er',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='pax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='recogido',
            field=models.BooleanField(default=False),
        ),
    ]
