# Generated by Django 5.1.7 on 2025-05-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='guia_general',
        ),
    ]
