# Generated by Django 5.1.7 on 2025-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0004_remove_pedido_guia_general"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="estado_cliente",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="estado_equipo",
        ),
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente_pago", "Pendiente de pago"),
                    ("pagado", "Pagado"),
                    ("aprobado", "Aprobado"),
                    ("entregado", "Entregado"),
                    ("recogido", "Recogido"),
                ],
                default="pagado",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
