# Generated by Django 5.1.7 on 2025-04-23 10:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def set_default_user(apps, schema_editor):
    Pedido = apps.get_model('pedidos', 'Pedido')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    default_user = User.objects.first()  # o filtra uno específico si sabes cuál
    for pedido in Pedido.objects.all():
        pedido.usuario = default_user
        pedido.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_stockcontrol_entregado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Cantidad de productos a entregar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guia',
            field=models.CharField(default='Sin asignar', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lugar_entrega',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lugar_recogida',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(set_default_user),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='pedidos', to='pedidos.producto'),
        ),
    ]
