# Generated by Django 5.1.7 on 2025-05-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_remove_pedido_estado_cliente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excursion",
                    models.CharField(max_length=120, verbose_name="Excursión"),
                ),
                ("pax", models.PositiveIntegerField(verbose_name="Pax")),
                (
                    "emisores",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Emisores"
                    ),
                ),
                (
                    "lugar_entrega",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Lugar de entrega"
                    ),
                ),
                (
                    "bono",
                    models.CharField(blank=True, max_length=60, verbose_name="Bono"),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="pedidos.pedido",
                    ),
                ),
            ],
            options={
                "ordering": ["excursion"],
            },
        ),
    ]
