# Generated by Django 5.1.7 on 2025-04-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_cantidad_pedido_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Maleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pax', models.IntegerField()),
                ('guia', models.CharField(max_length=255)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maletas', to='pedidos.pedido')),
            ],
        ),
    ]
