# Generated by Django 5.1.7 on 2025-05-21 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0006_servicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="productos",
        ),
        migrations.AddField(
            model_name="pedido",
            name="servicios",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Servicio"
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="cantidad_pax",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Cantidad de pax"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicio",
            name="guia",
            field=models.CharField(blank=True, max_length=120, verbose_name="Guía"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="excursion",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Excursión"
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="pax",
            field=models.PositiveIntegerField(verbose_name="PAX"),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios_linea",
                to="pedidos.pedido",
            ),
        ),
        migrations.DeleteModel(
            name="Maleta",
        ),
    ]
