# Generated by Django 5.1.7 on 2025-05-02 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_stockcontrol_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockcontrol',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockcontrol',
            name='fecha_er',
        ),
        migrations.RemoveField(
            model_name='stockcontrol',
            name='lugar_er',
        ),
        migrations.RemoveField(
            model_name='stockcontrol',
            name='pax',
        ),
        migrations.AddField(
            model_name='maleta',
            name='stock_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.stockcontrol'),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('G', 'Pagado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='lugar_recogida',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='excursion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='guia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='recogido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_especifica',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Fecha programada'),
        ),
        migrations.CreateModel(
            name='StockMaleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.CharField(max_length=100)),
                ('pax', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('maleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.maleta')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.stockcontrol')),
            ],
            options={
                'unique_together': {('stock', 'maleta')},
            },
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='maletas',
            field=models.ManyToManyField(through='pedidos.StockMaleta', to='pedidos.maleta'),
        ),
    ]
