# Generated by Django 5.1.7 on 2025-05-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_stockcontrol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='entregado',
            field=models.BooleanField(default=True),
        ),
    ]
