# Generated by Django 5.1.7 on 2025-05-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_stockcontrol_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcontrol',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
    ]
