# Generated by Django 5.1.7 on 2025-05-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_stockcontrol_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('Confirmado', '🟢 Confirmado'), ('entregado', '🔵 Entregado')], max_length=20),
        ),
    ]
