# Generated by Django 5.1.7 on 2025-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('Confirmado', '🟢 Confirmado'), ('entregado', '🔵 Entregado')], default='pendiente', max_length=20),
        ),
    ]
