# Generated by Django 5.1.7 on 2025-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='excursion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
