# Generated by Django 5.1.7 on 2025-05-12 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_pedido_excursion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maleta',
            name='stock_control',
        ),
        migrations.RemoveField(
            model_name='stockmaleta',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockmaleta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockmaleta',
            name='maleta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ultima_actualizacion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_cliente',
            field=models.CharField(choices=[('pendiente', '🟡 Pendiente'), ('pagado', '🟢 Pagado'), ('entregado', '🔵 Entregado')], default='pagado', max_length=20, verbose_name='Estado cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_equipo',
            field=models.CharField(choices=[('por_revisar', '🔍 Por revisar'), ('aprobado', '✅ Aprobado'), ('entregado', '📦 Entregado'), ('recogido', '📥 Recogido')], default='aprobado', max_length=20, verbose_name='Estado equipo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guia_general',
            field=models.CharField(default='Sin asignar', max_length=100, verbose_name='Guía general'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='recogido',
            field=models.BooleanField(default=False, verbose_name='Recogido'),
        ),
        migrations.AlterField(
            model_name='maleta',
            name='cantidad_pax',
            field=models.PositiveIntegerField(verbose_name='PAX'),
        ),
        migrations.AlterField(
            model_name='maleta',
            name='guia',
            field=models.CharField(max_length=255, verbose_name='Guía'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='empresa',
            field=models.CharField(max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='excursion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Excursión'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='lugar_entrega',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lugar entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='lugar_recogida',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lugar recogida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='almacen',
            field=models.CharField(max_length=100, verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='registrocliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registrocliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='registrocliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado'),
        ),
        migrations.AlterField(
            model_name='registrocliente',
            name='nombre_usuario',
            field=models.CharField(max_length=150, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='registrocliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_especifica',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Para'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='StockControl',
        ),
        migrations.DeleteModel(
            name='StockMaleta',
        ),
    ]
